apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysecret
spec:
  encryptedData:
    PASSWORD: AgBnfSjEJQ8TLqaywNI3P8brNl5nY5MFvlokLKKsYKFU18NF0wyaPkcLCYfEeilqwFB+84axwZE9G6eqV07X1aeikz1+Lsuw30r96sIhXFsN7ySejAndIqqBIJdNaQh+OWcB7eOrfLMhhqRdzXABEf5D9m2P3N8z+7DheZ+BrblIEY86tbDK2BS7UeWDszjPa9fCHTIuDvhp/EGPmTpsvPhm/bapK4MOhuel6O5ebNw9Wjs92GkifAFGe+Yk5SJQpKYHNvXvdWrc0i+lIM09cHoURyuscyVnUqtFr0VykrE7vytdJejMpwwxeXOmtkahe3kk0FPdcejJ5q4PkNUPcoEVfLxdtTE5eJT5BFPGJpVhwqeAlMGw6q/lQryPYRmeH3lWVtEO1fmDbzCdUCWrI0DSGcxw+Kjuag9yLBwD+NekUi3NmYOi5YY4+VeZ0h8Eg5cnK3mWcNYR1O/TGwG2ShwiLbwhQ7eHblbDeWgETWO2AR/18y6bFk8wkeBjmG26sns1uJt/l7i6XJiCxcVEFViCOslC4GAZ+HMt8MWCYHZOqf77keRuRoLxb6BFKQRkqNQsvo2dCS7z0pA+1BZadvPZlNdKOakCsdAOubzbO9hNFS7bjghftldjvok3SZeeR79+/82s2imASQaSmfbefhT10Z2rGvDRV62JqRpY5Y8mOJqEUNcZ4uPb3+/CQR9KdN9nqH8CeJ4bBequ2Yw=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default

