apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
- ../../day04 

commonLabels:
   team: eng

namePrefix: eng-

replicas: 
- name: dov-deploy
  count: 3

images:
- name: stackupiss/dov-bear
  newTag: v2

